#! /bin/bash

export GLASS_SHADER_PATH=build
export MALLOC_CHECK_=2

if [ "$GLASS_DMALLOC" ]; then
  eval "$(dmalloc -l ./logfile -i 100 high)"
fi
  
. ./build/env/bin/activate

export PATH=$(pwd)/build:$PATH

ulimit -c unlimited

if [ -e ~/.config/glass/session.sh ]; then
  . ~/.config/glass/session.sh
fi

glass-config-init
glass-session
